// Fable 5.1 — 100 HTML studies
// accent = the study's background color, extracted from its CSS :root / body background
// Generated from github.com/MiaAI-Lab/Fable-5.1-100-HTML-Files
const ROOMS = [
  { name: '001-aurora-glass', accent: '#070a1c', title: 'Lumen — Ambient Light OS', where: 'Fable 5.1 · Study 001', blurb: 'A quiet, luxurious glassmorphism hero where slow, hue-shifting aurora ribbons drift behind frosted panels that lean gently with the cursor. The composition relies on generous whitespace, a single shimmering word in the headline, and a small cast of accent colours to feel premium rather than busy, wi' },
  { name: '002-brutalist-manifesto', accent: '#fff', title: 'HONEST DESIGN — A Manifesto in Nine Parts', where: 'Fable 5.1 · Study 002', blurb: 'A loud, honest, paper-and-ink manifesto page where every box admits it is a box. Massive compressed uppercase type, raw monospace copy, 4px black rules and hard offset shadows are punctuated by only two accent colours, and the deliberately broken grid, spinning asterisk and distressed red stamp give' },
  { name: '003-neumorphic-audio-console', accent: '#dbe3ec', title: 'Softdesk 4 — Neumorphic Audio Console', where: 'Fable 5.1 · Study 003', blurb: 'A calm, tactile mixing desk carved from a single sheet of warm grey, where every knob, fader, switch and button reads as either extruded or pressed into the surface purely through paired light and dark shadows. The controls are genuinely operable and their state feeds a living signal engine so the m' },
  { name: '004-neon-cyberpunk-terminal', accent: '#05060a', title: 'KESTREL//OS — Boot Terminal', where: 'Fable 5.1 · Study 004', blurb: 'A theatrical, fully offline hacker-terminal experience: a CRT-textured black screen where a fictional OS boots itself with typewriter checks and progress bars before handing control to an interactive prompt, while the header glitches with magenta and cyan fringing, a wireframe icosahedron turns in t' },
  { name: '005-liquid-metal-blob', accent: '#1b1c1f', title: 'MERCURY — Liquid Metal Study', where: 'Fable 5.1 · Study 005', blurb: 'A meditative, full-screen study in fake physically based shading: pools of quicksilver glide across dark charcoal, fusing and splitting along a metaball threshold while a painted horizon slides across their skins, complete with a razor-bright horizon line, cool rim light and a hard specular glint. A' },
  { name: '006-particle-constellation', accent: '#fff', title: 'Constellation — An Interactive Particle Field', where: 'Fable 5.1 · Study 006', blurb: 'A meditative full-screen constellation simulator on a navy void, where hundreds of twinkling particles drift on a slow current, weave periwinkle threads with their neighbours, lean toward or away from the cursor, and scatter in glowing rings when clicked — framed by a thin serif title, a monospace t' },
  { name: '007-editorial-magazine-spread', accent: '#9aa4ab', title: 'The Quiet Architecture of Fog — Issue 14 · Margin', where: 'Fable 5.1 · Study 007', blurb: 'A cream-paper editorial feature with a towering black serif headline, an italic standfirst, a drop-capped essay flowing through one to three hairline-ruled columns, two column-spanning italic pull quotes, three abstract slate-and-bone "photographic" plates composed purely in CSS gradients, small-cap' },
  { name: '008-minimal-luxury-watch', accent: '#0a0a0b', title: 'Halden — Meridian 38 · Automatic', where: 'Fable 5.1 · Study 008', blurb: 'An ultra-minimal, near-black luxury product page built around a large, genuinely functional analog watch — brushed conic-gradient steel bezel, leather straps with stitch lines, a Roman-numeral dial with a sweeping gold seconds hand, glass reflection and live date — beside a quiet column of tracked s' },
  { name: '009-morphing-gradient-mesh', accent: '#161009', title: 'Breathe — A Living Gradient Mesh', where: 'Fable 5.1 · Study 009', blurb: 'A full-screen, ever-shifting mesh of five heavily blurred, screen-blended colour blobs drifting on slow eased orbits beneath a flickering canvas grain and a soft vignette, with a giant italic serif word crossfading every few seconds through a sequence of breathing prompts, a three-palette switcher (' },
  { name: '010-paper-cut-layers', accent: '#161009', title: 'Valley of Paper — A Layered Paper-Cut Dusk', where: 'Fable 5.1 · Study 010', blurb: 'A storybook paper-cut valley — eight stacked SVG sheets of mountains, hills, pines, a cabin and a deer, each with a soft cut-card shadow — beneath a paper sun, a rising crescent moon, and slow drifting paper clouds, where the pointer or device tilt shifts the layers at different depths and a gradien' },
  { name: '011-retro-crt-arcade', accent: '#030a05', title: 'NEON DRIFT — Attract Mode', where: 'Fable 5.1 · Study 011', blurb: 'A love letter to arcade cabinets: a chunky charcoal bezel frames a glowing green phosphor screen dressed with scanlines, aperture grille, vignette, roll bar and glass sheen, presenting a pixel logo, a keyboard-navigable menu, a cycling hi-score table, a blinking INSERT COIN, and a genuinely playable' },
  { name: '012-orbital-solar-system', accent: '#02030a', title: 'Orbit — A CSS 3D Solar System', where: 'Fable 5.1 · Study 012', blurb: 'A tranquil, planetarium-like solar system in which eight CSS-textured planets and Earth\'s moon circle a glowing corona-wrapped Sun on tilted 3D rings at their true relative speeds, seen from a draggable camera against a generated starfield, with a frosted-glass info card of real planetary facts on c' },
  { name: '013-flow-field-ink', accent: '#e9e3d6', title: 'Sumi Field — Generative Flow-Field Ink', where: 'Fable 5.1 · Study 013', blurb: 'A minimal ink-painting studio where seeded simplex noise guides thousands of tapering, dry-brush strokes across generated rice paper in three tonal passes, watched over by a vertical red seal bearing the seed number, with palette, turbulence, live particle flow, and PNG export controls in a quiet se' },
  { name: '014-kinetic-typography-poem', accent: '#0e0c0b', title: 'Nocturne for the Sea — a kinetic poem', where: 'Fable 5.1 · Study 014', blurb: 'A quiet nocturne in nine full-screen movements where each stanza of an original sea poem arrives through a different kinetic gesture — rising letters, sliding words, stretching tracking, 3D hinging, liquid fill, blur-surfacing, scatter-and-converge, sine-wave tide, and a final settling — under a fad' },
  { name: '015-isometric-city', accent: '#6b4a2b', title: 'Little Meridian — An Isometric City Block', where: 'Fable 5.1 · Study 015', blurb: 'A charming, pastel isometric city block built from CSS cuboids, where windows randomly flicker warm at night, long shadows swing with a simulated sun, glowing cars circle the streets, a pink neon sign bobs above a food hall, and any building springs up on hover to introduce itself, with pause, rain ' },
  { name: '016-fluid-smoke-touch', accent: '#04050a', title: 'Ether — Fluid Smoke Canvas', where: 'Fable 5.1 · Study 016', blurb: 'Ether is a dark, meditative full-screen canvas where the viewer paints with light: every drag pours slowly cycling neon dye into an incompressible fluid that curls, folds, and fades, while two invisible currents keep the void gently stirring. A restrained serif title and a frosted glass control card' },
  { name: '017-data-art-heartbeat', accent: '#161009', title: 'Pulse — A Portrait of One Heartbeat', where: 'Fable 5.1 · Study 017', blurb: 'Pulse is a quiet monitoring room rendered as art — a live ECG pen writes across glowing graph paper while a ring gauge, a breathing orb, and a day-long heart-rate landscape fill in the rest of a body\'s story; a three-way mode switch shifts the entire dashboard between the mint calm of rest, the cora' },
  { name: '018-bauhaus-composer', accent: '#161009', title: 'Komposition — Bauhaus Poster Composer', where: 'Fable 5.1 · Study 018', blurb: 'Komposition is a small design studio in a page: a strict grid, three primaries, five primitive shapes, and a seeded algorithm that arranges them into a fresh Bauhaus poster on demand, presented as a real sheet of textured paper beside a bold typographic manifesto column with wipe-fill buttons and a ' },
  { name: '019-zen-garden-sand', accent: '#161009', title: 'Karesansui — A Garden of Raked Sand', where: 'Fable 5.1 · Study 019', blurb: 'Karesansui turns the browser into a tray of warm, finely grained sand where the visitor\'s gestures become embossed rake grooves that flow around three dark stones, while the shadow of an unseen branch crosses the garden so slowly that time itself seems to be part of the composition; minimal serif ty' },
  { name: '020-glitch-art-portrait', accent: '#07070a', title: 'Signal Loss — Generative Glitch Portrait', where: 'Fable 5.1 · Study 020', blurb: 'Signal Loss hangs a procedurally painted portrait — nothing but ellipses, gradients, and grain — inside a corrupted transmission that tears it into shifted slices, split color channels, misplaced macroblocks, smeared ghosts of previous frames, and sudden inversions, all arriving in unpredictable bur' },
  { name: '021-holographic-card-gallery', accent: '#100818', title: 'Aurelian Codex — Holographic Card Gallery', where: 'Fable 5.1 · Study 021', blurb: 'A dark, jewel-box gallery of six fantasy trading cards that behave like real holographic foil: they tilt toward the pointer in 3D, a rainbow foil sheet and glitter pattern slide across the artwork as the angle changes, a specular highlight follows the fingertip, and the gilded frame glints. Clicking' },
  { name: '022-scroll-storytelling-ocean', accent: '#000', title: 'Descent — From the Sunlit Surface to the Challenger Deep', where: 'Fable 5.1 · Study 022', blurb: 'A vertical descent through the ocean\'s five pelagic zones, told through a fixed world that darkens as you scroll: turquoise becomes indigo becomes black, light rays dissolve, a depth meter and instruments count metres, pressure and temperature, and silhouetted sea life drifts past at parallax depths' },
  { name: '023-weather-dashboard-elegant', accent: '#161009', title: 'Port Ellery — Weather', where: 'Fable 5.1 · Study 023', blurb: 'A calm, editorial weather dashboard whose entire mood—background wash, accent colour, card tint—changes with the selected condition, anchored by a large hand-drawn animated weather icon and a serif temperature. Supporting instruments (smooth hourly curve, seven-day strip, wind compass, radial comfor' },
  { name: '024-voronoi-stained-glass', accent: '#1f3f9e', title: 'Rose of Cells — A Voronoi Stained-Glass Window', where: 'Fable 5.1 · Study 024', blurb: 'A generative gothic lancet window whose panes are Voronoi cells filled with jewel-toned glass, each pane shaded to look thicker at the edges and streaked like hand-rolled glass, all bound by heavy lead lines and framed by a pointed arch. A slow sheet of light sweeps across the panes, coloured light ' },
  { name: '025-typewriter-noir', accent: '#0e0e0e', title: 'The Castellane Photograph — A Noir Vignette', where: 'Fable 5.1 · Study 025', blurb: 'A black-and-white detective\'s office at two in the morning—rain on the window, blinds throwing amber bars across the desk, a cigarette smoking itself in the ashtray—where a short branching noir story types itself onto a sheet of paper with the uneven rhythm of a real machine, including sticky keys a' },
  { name: '026-swiss-grid-poster', accent: '#d9d9d9', title: 'Form Follows — Lecture Series 2026 · Swiss Grid Poster', where: 'Fable 5.1 · Study 026', blurb: 'A precise, high-contrast typographic poster where a single red accent, an enormous numeral and overlapping translucent plates create depth without decoration; the page doubles as a teaching artifact by exposing its own grid and re-composing itself on demand.

TECHNIQUES:
- 12-column × 24-row CSS Gri' },
  { name: '027-lava-lamp-css', accent: '#161009', title: 'Groovy Glow — Three CSS Lava Lamps', where: 'Fable 5.1 · Study 027', blurb: 'A cozy, nostalgic diorama where three brass-capped lava lamps glow against period wallpaper, their wax blobs merging and dividing through a pure CSS/SVG goo effect while soft light pools on the floor and the groovy gradient title hovers above.

TECHNIQUES:
- SVG goo filter (feGaussianBlur + feColorM' },
  { name: '028-generative-mandala', accent: '#1a1b1e', title: 'Kaleido — Symmetric Mandala Studio', where: 'Fable 5.1 · Study 028', blurb: 'A meditative digital drawing instrument where every gesture blossoms into a glowing radial pattern on a charcoal void, with a glassy pill toolbar and an autonomous mode that grows intricate multi-ring mandalas from noise.

TECHNIQUES:
- 2D canvas with per-copy setTransform for rotation and mirror re' },
  { name: '029-space-warp-tunnel', accent: '#000', title: 'Jumpgate — Hyperspace Warp Tunnel', where: 'Fable 5.1 · Study 029', blurb: 'A dark, high-contrast science-fiction jump sequence where star streaks stretch, a glowing wireframe tunnel rushes past and the horizon blooms white as the pilot holds the throttle, framed by a restrained monospace flight HUD.

TECHNIQUES:
- Pseudo-3D perspective projection of a star field with per-s' },
  { name: '030-ukiyo-e-great-wave', accent: '#2a231d', title: 'Nami no Yume — An Animated Ukiyo-e Seascape', where: 'Fable 5.1 · Study 030', blurb: 'A living woodblock print in which Prussian-blue swells with clawed cream foam roll beneath a pale mountain and drifting boats, complete with paper grain, a vermilion seal and vertical calligraphy, and a hover effect that lets the carved colour blocks slip out of register.

TECHNIQUES:
- Inline SVG w' },
  { name: '031-monochrome-portfolio', accent: '#a39e94', title: 'Ines Varga — Art Director', where: 'Fable 5.1 · Study 031', blurb: 'A severe, gallery-grade black-and-white portfolio that relies on typography, hairlines and a single warm grey to carry the entire visual identity, then layers in quiet, precise motion — a name that misregisters on hover, a cursor that becomes a "View" button, and abstract CSS artworks that glide aft' },
  { name: '032-synth-wave-visualizer', accent: '#05030a', title: 'NEON//OSC — Playable Synth', where: 'Fable 5.1 · Study 032', blurb: 'A neon-soaked, fully playable software synthesizer that generates every sound and every pixel in the browser — a glowing keyboard, tactile knob and toggles, waveform selector, and two live canvas visualizers (a gradient oscilloscope and a radial spectrum bloom) rendered in hot pink, lavender and ele' },
  { name: '033-double-pendulum-lab', accent: '#161009', title: 'Double Pendulum Laboratory — Chaos Instrument No. 7', where: 'Fable 5.1 · Study 033', blurb: 'A charcoal-and-brass instrument panel where a real RK4 double pendulum swings beneath a hatched pivot, its second bob painting a tapering rainbow ribbon, while a ruled laboratory notebook beside it lays out the Lagrangian equations in italic brass — and a copper twin offset by a thousandth of a radi' },
  { name: '034-vaporwave-sunset', accent: '#c0c0c0', title: 'ＬＵＮＡＲ ＷＩＮＤ — Vaporwave Sunset', where: 'Fable 5.1 · Study 034', blurb: 'A glowing vaporwave tableau — a striped gradient sun sinking into a pink haze above an endless cyan-and-pink neon grid that rushes toward the viewer, flanked by swaying palm silhouettes, watched over by a floating marble bust, and captioned by chrome full-width lettering — all controlled from a pixe' },
  { name: '035-art-deco-invitation', accent: '#161009', title: 'The Meridian Ball — An Invitation', where: 'Fable 5.1 · Study 035', blurb: 'A jet-black, gold-leafed Art Deco invitation card — sunburst rays turning behind a compass medallion, stepped borders, chevron bands and fan corners framing widely tracked serif lettering that shimmers like brushed metal — which pivots in three dimensions to reveal an elegant RSVP reply card, while ' },
  { name: '036-terrazzo-pattern-lab', accent: '#f7f3ea', title: 'Terrazzo Pattern Lab — Composite Stone Studio', where: 'Fable 5.1 · Study 036', blurb: 'A warm, gallery-like generative tool where a seeded canvas algorithm pours seamless terrazzo tiles from curated chip palettes, exposes tactile sliders and palette cards for tuning density, chip scale, speckle and binder colour, and immediately wraps the resulting texture around CSS-built mug, phone ' },
  { name: '037-northern-lights-canvas', accent: '#eef4ff', title: 'Northern Lights — Lake Inari, 68.9° N', where: 'Fable 5.1 · Study 037', blurb: 'A meditative full-screen canvas landscape in which layered noise-driven curtains of green and violet light drift over a black pine horizon and are mirrored in a still, faintly rippling lake, with twinkling stars, occasional meteors and slow snowfall, framed by a sparse serif caption and a single gla' },
  { name: '038-origami-fold-menu', accent: '#f7f3ec', title: 'Origami Fold Menu — Kami &amp;amp; Fold Paper Studio', where: 'Fable 5.1 · Study 038', blurb: 'A restrained paper-studio landing page whose navigation is a sculpted packet of five coloured sheets that swing out on vertical hinges and then drop their content in accordion folds, with two-sided textured paper, angle-driven shading, sequential staggering and full keyboard access, so the menu itse' },
  { name: '039-pixel-art-studio', accent: '#0d0e13', title: 'Pixel Art Studio — Sprite Editor', where: 'Fable 5.1 · Study 039', blurb: 'A polished dark-mode sprite editor where a crisp DPR-aware pixel grid, a curated 32-colour palette, six real drawing tools with mirror symmetry, undo/redo and nearest-neighbour PNG export are wrapped in soft glowing panels and pill controls, with live 1×/2× previews and a toggleable CRT-styled hero ' },
  { name: '040-topographic-contours', accent: '#f3eee3', title: 'Living Landscape — Animated Topographic Contours, Sheet 040', where: 'Fable 5.1 · Study 040', blurb: 'A full-screen, ever-shifting topographic map in which a time-evolving noise heightfield is rendered as hillshaded relief and traced by marching-squares contour lines, with thicker labelled index contours, a cursor spotlight that reads elevation, slope and aspect, three cartographic palettes and a sw' },
  { name: '041-spiral-galaxy-particles', accent: '#000000', title: 'NGC 7741 — Spiral Galaxy Particle Observatory', where: 'Fable 5.1 · Study 041', blurb: 'A full-screen additive-blended particle galaxy with two logarithmic spiral arms, warm core, blue star-forming knots and red outer dust, rotating differentially beneath a restrained observatory HUD whose statistics count up on load. The viewer tilts and spins the disk by dragging, zooms by scrolling,' },
  { name: '042-vintage-radio-tuner', accent: '#1c1108', title: 'Marconi Meridian 55 — Vintage Radio Tuner', where: 'Fable 5.1 · Study 042', blurb: 'A photoreal-feeling Bakelite radio built from CSS gradients and inline SVG: a glowing amber medium-wave dial with European city names, a draggable red needle and a big rotary tuning knob, a display window that hisses with canvas static between stations and lights a station card with a fictional prog' },
  { name: '043-life-garden-automaton', accent: '#7fb069', title: 'The Garden Automaton — Conway\'s Life as a Living Bed', where: 'Fable 5.1 · Study 043', blurb: 'A full-viewport Game of Life whose cells are luminous rounded blooms colouring from seedling green through coral and violet to elder gold as they age, leaving fading soil stains when they die, all framed with botanical-journal serif typography, a tempo slider, live generation and population counters' },
  { name: '044-honeycomb-hex-nav', accent: '#161009', title: 'Apiary Studio — Honeycomb Navigation', where: 'Fable 5.1 · Study 044', blurb: 'A viewport-filling honeycomb of CSS clip-path hexagons that lift, brighten and tilt toward the cursor with a rippling ease, six golden cells forming a navigation ring that morph into a rounded content card when chosen while the rest of the comb dims, all bathed in deep amber with a slow drifting lig' },
  { name: '045-cinematic-title-sequence', accent: '#000', title: 'The Long Meridian — Title Sequence', where: 'Fable 5.1 · Study 045', blurb: 'A letterboxed, fully time-driven film title sequence — grain, drifting fog, a growing horizon line, fading cast names, a blurred-to-sharp title with a light sweep and expanding tracking, a passing lens flare, thirty seconds of rolling crew credits and an end card — controlled by a cinematic timeline' },
  { name: '046-spectrum-palette-studio', accent: '#fff', title: 'Spectrum — Palette Studio', where: 'Fable 5.1 · Study 046', blurb: 'A refined color-palette workstation on a translucent, hue-tinted white canvas, where a draggable hue/saturation plane and lightness slider drive five harmony-derived swatches, a WCAG contrast table, a live-themed mini UI card, and a CSS-variables export — every surface of the page breathing gently t' },
  { name: '047-glass-music-player', accent: '#0b0a14', title: 'Lumen — Glass Music Player', where: 'Fable 5.1 · Study 047', blurb: 'A mobile-first frosted-glass music player floating over a slowly rotating, heavily blurred album-color disc, where each of eight fictional tracks carries its own gradient identity that washes through the vinyl, equalizer, progress bar and play button whenever the song changes, complete with real-tim' },
  { name: '048-brutalist-archive-index', accent: '#000', title: 'ARCHIVE / 1972–2026', where: 'Fable 5.1 · Study 048', blurb: 'A stark black-on-white archive index where a monospace table of forty fictional holdings meets rigorous Helvetica headlines, hairline rules, a live clock and a huge sticky masthead; each row hovered inverts to black and conjures a unique procedural artifact — layered CSS gradient patterns seeded fro' },
  { name: '049-fireflies-night-meadow', accent: '#05081a', title: 'Night Meadow — Fireflies', where: 'Fable 5.1 · Study 049', blurb: 'An immersive nocturnal meadow where hundreds of procedurally drawn SVG grass blades sway in staggered rhythm beneath a moonlit gradient sky and rolling hills, while dozens of canvas fireflies wander and pulse in soft yellow-green light, scattering from the cursor\'s breeze, bursting into new swarms o' },
  { name: '050-clock-collection', accent: '#0e0f13', title: 'Twelve Ways to Tell the Time — A Clock Collection', where: 'Fable 5.1 · Study 050', blurb: 'A dark, serif-framed gallery of twelve live clocks, each on a card with its own palette and material — Swiss railway enamel, glowing word grid, binary LEDs, daylight arc, orange nixie glass, orbiting rings, split-flap cards, polar dots, plain English prose, a 24-hour day/night dial, an emptying hour' },
  { name: '051-mondrian-composer', accent: '#f6f3ec', title: 'Composer — A De Stijl Generator', where: 'Fable 5.1 · Study 051', blurb: 'A quiet, gallery-lit generative painting: a black-gutter grid of off-white canvas planes with a few decisive primaries, framed and hung on a plaster wall under a soft spotlight, with an authentic museum wall plate that rewrites its own title as you recolor the work.

TECHNIQUES:
- CSS Grid with `gap' },
  { name: '052-rain-on-window', accent: '#05070f', title: 'Night Window — Rain on Glass', where: 'Fable 5.1 · Study 052', blurb: 'A cinematic, cozy loop of rain running down a night window: a blurred city of twinkling bokeh behind the pane, physically plausible refractive raindrops that grow, merge, slide and streak through condensation, and a warm lamp reflected faintly in the glass — with the viewer able to wipe the fog by h' },
  { name: '053-mandelbrot-explorer', accent: '#07080c', title: 'Mandelbrot Explorer — Progressive Fractal Renderer', where: 'Fable 5.1 · Study 053', blurb: 'A crisp, dark, instrument-like fractal viewer: a multi-threaded, progressively refining Mandelbrot canvas with smooth continuous coloring and four curated palettes, framed by frosted glass panels, monospaced coordinate readouts, and a strip of thumbnail bookmarks leading to the set\'s most celebrated' },
  { name: '054-magnetic-microinteractions', accent: '#f6f6fb', title: 'Small Joys — Ten Microinteractions', where: 'Fable 5.1 · Study 054', blurb: 'A bright, restrained gallery of ten tactile UI moments — magnetic pulls, liquid squashes, drawn checks, particle bursts and morphing progress — each isolated on a card with a short caption, tuned with spring physics so every element feels like it has weight and rubbery life.

TECHNIQUES:
- Shared JS' },
  { name: '055-newspaper-front-page', accent: '#2b2420', title: 'The Meridian Gazette — Thursday, October 14, 1926', where: 'Fable 5.1 · Study 055', blurb: 'A convincingly aged 1926 broadsheet — coffee-ringed, grain-textured and creased — with a blackletter masthead, justified multi-column fictional news of a transatlantic airship, a hatched SVG engraving, weather and stock boxes, quaint classifieds and a distressed red "Late Edition" stamp, all typeset' },
  { name: '056-cube-carousel-3d', accent: '#000', title: 'Halden &amp;amp; Voss — Six Works in Concrete, Timber and Light', where: 'Fable 5.1 · Study 056', blurb: 'A monumental, gallery-like 3D carousel where an architecture studio\'s six projects are printed as bold graphic posters on the faces of a rotating hexagonal prism, standing on a mirrored concrete floor under a drifting amber light. The mood is quiet, heavy and precise — concrete, steel and warm brass' },
  { name: '057-lsystem-tree-growth', accent: '#161009', title: 'Arbor recursiva — A Generative L-System Botanical Plate', where: 'Fable 5.1 · Study 057', blurb: 'A living botanical illustration: a stochastic L-system tree grows branch by branch on aged paper inside an engraved frame, with its Latin name and its own grammar printed as the plate caption. Seasons repaint the canopy from cherry-pink to amber to snow, the wind makes the whole hierarchy sway, and ' },
  { name: '058-led-matrix-marquee', accent: '#0c0d0f', title: 'DOTMATRIX-7 — LED Marquee Controller', where: 'Fable 5.1 · Study 058', blurb: 'A lovingly detailed emulation of a station-platform LED sign: warm amber dots glow behind glass in a brushed-steel bezel with real screws, scrolling whatever the user types in a hand-drawn 5×7 pixel font, while a second display keeps time. The console beneath feels like industrial hardware — segment' },
  { name: '059-coastal-luxury-hotel', accent: '#fff3dd', title: 'Casa Maré — A Quiet House Above the Atlantic', where: 'Fable 5.1 · Study 059', blurb: 'A serene, editorial hotel website where the sea is rendered in code: a gradient sky, a breathing sun glint and three drifting SVG wave bands set the scene, and everything below — abstract room "photographs", a tide-table of experiences, a working booking calculator and a hand-drawn coastline map — f' },
  { name: '060-digital-rain-typeface', accent: '#04100c', title: 'RAIN.TYPE — Digital Rain as Typographic Art', where: 'Fable 5.1 · Study 060', blurb: 'A meditative, elegant take on falling code: columns of invented glyphs and letters pour down in jade, amber, ice or rose, each with a bright glowing head and a long dissolving tail, until the visitor types a phrase and watches the rain gather itself into words — letters snapping into place with a po' },
  { name: '061-leather-field-notebook', accent: '#fbf9f4', title: 'Field Notebook — The Saltmarsh Walk', where: 'Fable 5.1 · Study 061', blurb: 'A tactile, romantic object page: a well-loved leather notebook that opens in true 3D to reveal ruled cream pages filled with slanting blue handwriting, pressed flowers, a taped-in polaroid and coffee rings, telling the small story of a weekend\'s walk along a saltmarsh coast, with realistic page turn' },
  { name: '062-harmonograph-drawing', accent: '#3a2a0a', title: 'The Harmonograph — A Pendulum Drawing Instrument', where: 'Fable 5.1 · Study 062', blurb: 'A luminous, meditative instrument page where glowing decaying pendulum curves bloom slowly on a smoked-glass plate set into a mahogany bed, controlled from an engraved brass panel of sliders, ink swatches and pressed-bronze buttons — equal parts Victorian laboratory and generative art tool.

TECHNIQ' },
  { name: '063-holographic-concert-ticket', accent: '#161009', title: 'NOVA SYNDICATE — Holographic Admission', where: 'Fable 5.1 · Study 063', blurb: 'A luxurious, oversized holographic admission ticket for a fictional synth-pop act, glowing under aubergine stage haze, that tilts in 3D toward your hand, shimmers with a masked rainbow foil and glare, and can be physically torn along its perforation with a satisfying, jittery, physics-driven flop of' },
  { name: '064-desert-dunes-parallax', accent: '#161009', title: 'Sahel Meridian — Dunes at Golden Hour', where: 'Fable 5.1 · Study 064', blurb: 'A serene, cinematic desert vista built entirely from gradients, SVG curves and canvas particles: six graduated dune silhouettes drift in parallax under a sun that sinks through a sixty-second sunset, the horizon wavers with heat shimmer, sand streams across the foreground on a gusting wind, and a ti' },
  { name: '065-neural-network-visualizer', accent: '#fff', title: 'Synapse — A Living Neural Network', where: 'Fable 5.1 · Study 065', blurb: 'A glowing, data-true visualization of a five-layer neural network learning XOR-like problems in real time: weights thicken and flip between cyan and magenta as backpropagation runs, activation pulses stream across the Bézier synapses on demand, a loss curve draws itself, and a decision-boundary heat' },
  { name: '066-typographic-word-clock', accent: '#ffd68a', title: 'Word Clock — A Typographic Time Poem', where: 'Fable 5.1 · Study 066', blurb: 'A meditative, museum-quality word clock: a glowing grid of heavy geometric letters spelling out the time in words, floating over a sky whose colours drift with the actual hour, accompanied by a quietly generated line of poetry about the moment of day, and celebrated each minute with a soft rain of l' },
  { name: '067-cosmic-cursor-trail', accent: '#000', title: 'Stardust — Cosmic Cursor Trail', where: 'Fable 5.1 · Study 067', blurb: 'A black void that remembers every gesture as luminous dust: moving the pointer scatters additive-glow particles that inherit its speed and slowly change colour, a spring-lagged comet chases the hand, holding the button winds a swirling vortex that bursts on release, and when the viewer rests, a ghos' },
  { name: '068-kaleidoscope-mirror', accent: '#0e0c0a', title: 'Kaleidoscope — A Brass Eyepiece of Living Glass', where: 'Fable 5.1 · Study 068', blurb: 'A deep-brown room with a single brass kaleidoscope: inside its glass, jewel-coloured blobs and shards drift and rotate, mirrored six to twelve times into ever-changing mandalas that the viewer turns simply by moving the pointer, while the brass rim glints and the whole pattern slowly wheels on its o' },
  { name: '069-periodic-table-elegant', accent: '#1b2130', title: 'The Elements — An Elegant Periodic Table', where: 'Fable 5.1 · Study 069', blurb: 'A museum-label take on the periodic table: 118 quietly coloured tiles in the classic silhouette on dark slate, where hovering any element lifts it and conjures a spinning Bohr atom with the correct number of electrons in a card tucked into the table\'s natural gap, and where a temperature slider melt' },
  { name: '070-ink-drop-diffusion', accent: '#e7edf0', title: 'Sumi — Ink Drops in Still Water', where: 'Fable 5.1 · Study 070', blurb: 'A still surface of pale water that accepts each touch as a drop of ink: the blot blooms into tendrils driven by curl noise, overlapping colours mix like real pigment, and the whole pool turns imperceptibly so the marks soften and drift; switch to paper and the same ink bleeds into cream fibres with ' },
  { name: '071-atomic-age-retro-futurism', accent: '#161009', title: 'Stellar Motor Lodge &amp;amp; Observatory — Tomorrow\'s Hospitality, Today', where: 'Fable 5.1 · Study 071', blurb: 'A cream-and-charcoal landing page for an imaginary 1957 motel-with-a-telescope, built from googie architectural cues — an angled clip-path roof, a flickering neon vacancy sign, boomerang and starburst ornaments, an orbiting-electron atom, a spinning satellite and a launchable rocket — with italic se' },
  { name: '072-wireframe-terrain-flight', accent: '#000', title: 'Vector Horizon — Endless Wireframe Terrain Flight', where: 'Fable 5.1 · Study 072', blurb: 'A meditative, arcade-tinged flight over a neon wireframe world that never ends: glowing ridgelines pour toward the viewer under a banded synthwave sun, the whole horizon banking as you steer, with fog swallowing the far grid and white speed streaks appearing when you push the throttle, all framed by' },
  { name: '073-candle-meditation', accent: '#e9caa9', title: 'Still Flame — A Candle Breathing Guide', where: 'Fable 5.1 · Study 073', blurb: 'A hushed, warm digital candle whose layered, randomly flickering flame lights a dark room and gently expands and contracts to lead the viewer through 4-7-8, box or calm breathing, complete with a thin progress ring, whispering serif cues, slowly lengthening wax drips, and a blow-to-extinguish intera' },
  { name: '074-transit-map-live', accent: '#161009', title: 'Vellmar Metro — Live Network Map', where: 'Fable 5.1 · Study 074', blurb: 'A polished, official-feeling schematic transit diagram for an imaginary city, rendered entirely in inline SVG with six colored 45°-geometry lines, interchange discs and tick stations, along which tiny trains glide and pause at every stop; hovering isolates a line, clicking a station opens a live cou' },
  { name: '075-market-data-art', accent: '#07080a', title: 'Aurum — Market Data as Abstract Art', where: 'Fable 5.1 · Study 075', blurb: 'A dark, luxurious dashboard-as-artwork in which a volatility-clustered random walk paints thin glowing candlesticks, a breathing mirrored order book, a live-recoloring sector treemap and a gliding ticker tape, while every simulated trade sends a faint mint or rose sonar ring rippling across the obsi' },
  { name: '076-chladni-resonance', accent: '#0b0c0e', title: 'Chladni Resonance — Sand on a Singing Plate', where: 'Fable 5.1 · Study 076', blurb: 'A dark, instrument-like laboratory page where a brushed-metal plate is dusted with fourteen thousand grains of simulated sand. As the user changes the vibrational modes or lets the frequency sweep, the grains flee the glowing antinodes and settle into ever-changing Chladni figures, while brass dials' },
  { name: '077-wooden-toy-blocks', accent: '#fff', title: 'Wooden Alphabet Blocks — A Tumbling Toy', where: 'Fable 5.1 · Study 077', blurb: 'A bright, warm nursery scene where hand-painted wooden alphabet cubes tumble, stack and topple on a wood desk under morning light. Users toss blocks around, spell words that rain down from above and shake the table to send everything wobbling, with chunky rounded controls that feel like toys themsel' },
  { name: '078-lighthouse-storm-night', accent: '#030710', title: 'The Keeper\'s Light — A Lighthouse in a Night Storm', where: 'Fable 5.1 · Study 078', blurb: 'A moody, cinematic seascape at midnight: rain lashes across the frame at a wind-driven angle, waves heave against black rocks, a sweeping cone of warm light rakes through cloud and rain from a red-and-white lighthouse, and lightning periodically whites out the scene with a thunderous shake. A small ' },
  { name: '079-recipe-editorial-card', accent: '#fff', title: 'Saffron &amp;amp; Blood Orange Tart — An Editorial Recipe', where: 'Fable 5.1 · Study 079', blurb: 'A luxurious, print-inspired recipe spread on cream paper where a fully CSS-drawn saffron tart crowned with blood orange wheels anchors an elegant serif layout. Ingredients tick off with a growing orange strike, quantities rescale with pretty fractions, and a cook mode with ring timers turns the edit' },
  { name: '080-boids-murmuration', accent: '#161009', title: 'Murmuration — Starlings at Dusk', where: 'Fable 5.1 · Study 080', blurb: 'A dusk-to-night sky above a silhouetted treeline and telegraph wires where thousands of tiny triangles behave as a single breathing organism, thickening into ink-black cores and thinning to smoke at the edges. The viewer\'s pointer becomes a hawk that tears holes in the flock, while a hushed glass pa' },
  { name: '081-gothic-rose-window', accent: '#161009', title: 'Rosace du Nord — A Gothic Rose Window', where: 'Fable 5.1 · Study 081', blurb: 'A luminous, meditative stained-glass rose window whose jewel panes glow as an unseen sun crosses behind them, spilling blurred colour onto a stone floor while dust drifts through the light; every pane is a small story you can discover by hovering.

TECHNIQUES:
- Inline SVG with &lt;symbol&gt;/&lt;use&gt; rotati' },
  { name: '082-prism-light-dispersion', accent: '#06070b', title: 'Dispersion — An Interactive Prism', where: 'Fable 5.1 · Study 082', blurb: 'A dark, cinematic optics bench where a draggable lamp fires white light through a glowing glass prism that fans it into a physically traced spectrum on a screen, with lens flares, drifting caustics, a mirrored floor, and a hover readout that names each wavelength.

TECHNIQUES:
- Canvas ray tracing w' },
  { name: '083-terminal-portfolio', accent: '#282a36', title: 'nova@portfolio — zsh', where: 'Fable 5.1 · Study 083', blurb: 'A polished, glassy macOS-style terminal that doubles as a portfolio — you type commands to reveal a typed ASCII logo, animated skill bars, project cards, contact details, four colour themes and a Matrix easter egg, all inside a single self-contained page with a fake dock and a gradient desktop.

TEC' },
  { name: '084-cherry-blossom-drift', accent: '#161009', title: 'Sakura Drift — petals, river, breeze', where: 'Fable 5.1 · Study 084', blurb: 'A serene layered sakura landscape — indigo branches heavy with gradient blossoms, a pagoda in the mist, a sky warming from morning to gold — where hundreds of fluttering petals respond to your hand, land on a rippling river and drift away while a haiku writes itself in vertical script.

TECHNIQUES:
' },
  { name: '085-tarot-arcana-flip', accent: '#161009', title: 'The Major Arcana — a three-card spread', where: 'Fable 5.1 · Study 085', blurb: 'A luxurious, candle-lit tarot table where twenty-two hand-drawn gold-line arcana fan out across burgundy velvet, fly into a past-present-future spread, and flip in 3D with a foil shimmer to reveal original, evocative readings — reversed cards included.

TECHNIQUES:
- Layered CSS velvet: crossed repe' },
  { name: '086-reaction-diffusion-skin', accent: '#050505', title: 'Specimen 086 — Reaction-Diffusion Skin', where: 'Fable 5.1 · Study 086', blurb: 'A living specimen slide: a Gray-Scott reaction-diffusion field grows coral, leopard and fingerprint textures in real time inside a glass square set into a charcoal slide with an engraved brass label, surrounded by lab-monospace readouts. Preset cultures, a continuous f/k parameter pad, four stain pa' },
  { name: '087-mid-century-modern-poster', accent: '#f3e5c3', title: 'Three Journeys — Mid-Century Travel Poster Series', where: 'Fable 5.1 · Study 087', blurb: 'A horizontal snap-scroll gallery of three hand-composed mid-century travel posters — a mustard Lisbon tram under a yolk sun, a vermilion Kyoto torii beneath a cream moon and drifting maples, and geometric Reykjavik mountains under swaying aurora ribbons — each built from flat geometric inline SVG wi' },
  { name: '088-snow-globe-shake', accent: '#161009', title: 'Winter, Kept — An Interactive Snow Globe', where: 'Fable 5.1 · Study 088', blurb: 'A glass snow globe on a walnut-and-gold music-box base in a dark teal room full of amber bokeh. Inside, a lit cottage, pines and a lamp post wait beneath canvas snow that rests on the ground until you shake the globe — by fast drag, button or device motion — whereupon a turbulent flurry erupts and s' },
  { name: '089-mini-synth-keyboard', accent: '#141312', title: 'MS-2 Duet — Mini Analog-Style Synthesizer', where: 'Fable 5.1 · Study 089', blurb: 'A warm walnut-and-brushed-aluminium desktop synthesizer with screen-printed labels, knurled draggable knobs, rubber buttons and glowing LEDs, offering a two-octave playable keyboard, four oscillator shapes with detune and glide, an ADSR with a live envelope graph, a resonant low-pass with a computed' },
  { name: '090-bioluminescent-deep-sea', accent: '#020611', title: 'Abyssal — Bioluminescent Deep Sea', where: 'Fable 5.1 · Study 090', blurb: 'A silent, nearly black ocean trench rendered on canvas: translucent jellyfish built from additive radial gradients pulse upward trailing Verlet-chain tentacles, glowing plankton drift in a slow current and scatter brightly from the cursor, a faint blue light shaft sways from far above, and every so ' },
  { name: '091-blueprint-schematic-draw', accent: '#161009', title: 'Pavilion 07 — Self-Drawing Blueprint', where: 'Fable 5.1 · Study 091', blurb: 'A luminous cyanotype drawing sheet where a modernist reading pavilion sketches itself line by line: heavy walls first, then furniture, hatching and dimension arrows, then annotations that type themselves in. Three sheets (plan, elevations, section) can be switched with a full redraw, rooms respond t' },
  { name: '092-gradient-type-hero', accent: '#161009', title: 'Grain &amp;amp; Ligature — Type Foundry', where: 'Fable 5.1 · Study 092', blurb: 'A dark, sophisticated type-foundry hero where one enormous word glows with a peach-to-ice gradient that shifts with the cursor like light moving across a printed poster. The five letters drift softly, respond to hover with scale, tilt and a glyph tooltip, and the rest of the page reads like a printe' },
  { name: '093-pomodoro-zen-timer', accent: '#161009', title: 'Stillwater — Focus Timer', where: 'Fable 5.1 · Study 093', blurb: 'A meditative Pomodoro timer whose whole colour temperature drifts as the session elapses, centred on a gradient progress ring with an orbiting gleam and ultra-thin tabular numerals. Focus, short-break and long-break modes are editable; the play/pause icon morphs; breaks breathe a soft halo; completi' },
  { name: '094-pop-art-halftone', accent: '#fff', title: 'DOT BOMB — Pop-Art Halftone Studio', where: 'Fable 5.1 · Study 094', blurb: 'A loud, joyful halftone laboratory in the spirit of Lichtenstein and Warhol. A procedurally drawn portrait, shape composition or typed word is split into ink channels and re-screened as rotated dot lattices whose dot size carries tone, wrapped in heavy Sobel-derived comic outlines and topped with a ' },
  { name: '095-string-art-loom', accent: '#f0cc7a', title: 'Tension — String Art Loom', where: 'Fable 5.1 · Study 095', blurb: 'A meditative generative loom that recreates a portrait, orb or ring pattern out of thousands of straight threads stretched between nails on a hand-painted wooden board. The greedy weaver works visibly, thread by thread, with a live counter; visitors can change frame shape, nail count, thread colour ' },
  { name: '096-thermal-vision-heatmap', accent: '#07080a', title: 'THERMA-1 — Thermal Vision Heatmap', where: 'Fable 5.1 · Study 096', blurb: 'A retro-industrial thermal-imager simulation: a rounded dark bezel frames a 16:9 sensor feed where the visitor\'s cursor warms a diffusing heat grid rendered through an iron false-colour palette, while ghostly warm figures pace behind the "wall" and clicked embers bloom and cool, all annotated by a l' },
  { name: '097-planetarium-star-chart', accent: '#161009', title: 'Planetarium — An Interactive Star Chart', where: 'Fable 5.1 · Study 097', blurb: 'A midnight-blue planetarium dome ringed in engraved brass, where nearly a hundred real stars and ten constellations wheel slowly with sidereal time over a soft Milky Way and dashed ecliptic; visitors scrub the hour, date and latitude, toggle figures and labels, and hover any bright star to read its ' },
  { name: '098-memphis-design-party', accent: '#fff', title: 'TOTALLY SATURDAY — A Memphis Design Party', where: 'Fable 5.1 · Study 098', blurb: 'A Memphis Group party poster brought to life: sixteen spring-physics geometric shapes in pink, teal, yellow, lavender and black bounce and rearrange on hover and click over a terrazzo-speckled cream ground, beneath a chunky offset-shadowed "TOTALLY SATURDAY" headline with a self-drawing squiggle, a ' },
  { name: '099-water-ripple-reflection', accent: '#161009', title: 'Still Water — Moonlit Ripple Reflection', where: 'Fable 5.1 · Study 099', blurb: 'A serene interactive nocturne: a silver moon, star field, ridge and treeline are mirrored in a lake whose surface is a real two-buffer ripple simulation, so every click or drag sends rings that bend the reflection and set the moon\'s light path shimmering, while amber lanterns drift on the far shore ' },
  { name: '100-organic-wave-lab', accent: '#0b0d14', title: 'Organic Wave Lab — Compose Layered Waveforms', where: 'Fable 5.1 · Study 100', blurb: 'An expansive, gallery-quality wave composer: up to six gradient-filled organic waveforms flow across the entire viewport under screen, multiply or additive blending, styled by five presets from warm dunes to aurora and nebula; a frosted glass panel with reorderable layer chips and thin small-caps co' }
];
